# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OntarioGeohub
                                 A QGIS plugin
 A plugin to import layers from Ontario Geohub LIO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-16
        copyright            : (C) 2025 by EcoGIS Helpers
        email                : aidan.w.obrien@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OntarioGeohub class from file OntarioGeohub.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geohub_services import OntarioGeohub
    return OntarioGeohub(iface)
